version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/angular"
    schedule:
      interval: "weekly"
    groups:
      npm_and_yarn:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/src/python"
    schedule:
      interval: "weekly"
